### ISSUE TITLE
overflow when compiling on rust 1.32.0

### ISSUE THREAD

**Issue by jnises** [Michael-F-Bryan/include_dir#34]
I am unable to compile a project using include_dir with the error message `thread 'main' has overflowed its stack` on rust version 1.32.0
1.31 still worked.
I am using the toolchain stable-x86_64-pc-windows-msvc.
Here is a repo reproducing the issue: https://github.com/moushkka/include_dir_overflow_test
Removing the file `stuff/jstree.min.js` from that repo before compiling solves the issue, indicating that the files need to be of a certain size to cause it.
`jstree.min.js` is in this case 136K

**Comment by JonBoyleCoding** [comment]
I also have this issue. Trying to use a folder with a TTF file that's 213KB.

**Comment by Michael-F-Bryan** [comment]
That's weird. I'm using `rustc 1.34.0-nightly (00aae71f5 2019-02-25)` and, even though `include_dir_overflow_test` took 5 minutes, 25 seconds to compile (!!!!) it didn't overflow.

This might be a `rustc` bug because the `include_dir!()` macro just recursively traverses a directory and creates a bunch of static `File` variables using `include_bytes!()` to embed the actual file contents. 

So your example should expand to (roughly) the following:

```rust
static DIR: Dir = Dir {
    path: "stuff",
    files: &[
        File {
            path: r"stuff/jstree.min.js",
            contents: include_bytes!(r"../stuff/jstree.min.js"),
        },
        File {
            path: r"stuff/test.txt",
            contents: include_bytes!(r"../stuff/test.txt"),
        },
    ],
    dirs: &[],
};
```

I *think* `rustc` is seeing the `include_bytes!()` macro and choosing to expand that too early, leading to a really massive array literal which causes the rest of parsing to take forever. 

It took 4 minutes and 50 seconds, but I also ran `include_dir_overflow_test` through `cargo expand`. According to `wc`, the expanded text is roughly 11841 lines long (1151405 bytes - 1.2MB).

[expanded.txt](https://github.com/Michael-F-Bryan/include_dir/files/2906058/expanded.txt)

**Comment by Michael-F-Bryan** [comment]
After merging #66 I can no longer reproduce this issue.
