### ISSUE TITLE
Strange Path Separator with Webassembly

### ISSUE THREAD

**Issue by Sirius902** [Michael-F-Bryan/include_dir#40]
I was testing this crate with a Webassembly project and noticed that with the following code the call to `get_file` returns `None`.
```rust
#[macro_use]
extern crate stdweb;

#[macro_use]
extern crate include_dir;
use include_dir::Dir;

pub const FOO: Dir = include_dir!("foo");

fn main() {
    console!(log, format!("{:#?}", FOO.get_file("foobar/bar.txt")));
}
```
But when I instead pass `"foobar\\bar.txt"` to `get_file` instead it returns the file even though `std::path::MAIN_SEPARATOR` is `'/'`. This means that passing `Path::new("foobar").join("bar.txt")` to `get_file` does not work either.

**Comment by Michael-F-Bryan** [comment]
Hmm... I think this would happen because `include_dir!()` runs on the host machine (e.g. windows, where the separator is `\`) but the `get_file()` method is called on the target machine (wasm, where the separator is `/`).

I guess we could work around this by making either `get_file()` not care about the path separator or storing the paths in a cross-platform format (e.g. `&["foo", bar.txt"]` or always using `/`)?

**Comment by Sirius902** [comment]
When I run the same project on Windows `"foobar/bar.txt"` works just fine so I'm not sure why.

**Comment by Sirius902** [comment]
@Michael-F-Bryan Maybe `get_file()` could use `std::path::MAIN_SEPARATOR` as separator so that you could use the `std::path::Path` from the standard library.
