### ISSUE TITLE
Feature request: tower compatible

### ISSUE THREAD

**Issue by Folyd** [Michael-F-Bryan/include_dir#79]
`tower-http` provides a handy [ServeDir](https://docs.rs/tower-http/latest/tower_http/services/fs/struct.ServeDir.html) to serve directory HTTP requests. I think we can also make the `Dir` tower compatible?

**Comment by Michael-F-Bryan** [comment]
What does *"make the `Dir` tower compatible"* mean?

**Comment by Folyd** [comment]
What i mean is this:
```diff
// This will serve files in the "assets" directory and
// its subdirectories
- let service = ServeDir::new("assets");
+ let service: Dir<'_> = include_dir::include_dir!("assets");

// Run our service using `hyper`
let addr = std::net::SocketAddr::from(([127, 0, 0, 1], 3000));
hyper::Server::bind(&addr)
    .serve(tower::make::Shared::new(service))
    .await
    .expect("server error");
```

**Comment by Michael-F-Bryan** [comment]
You will need create your own `tower-include-dir` crate which exposes a `tower::Service` implementation backed by `include_dir::Dir`. This is outside the scope of the `include_dir` project.

**Comment by Folyd** [comment]
Ok, I see. It's possible to make this under the `tower` feature flag in this crate? If so, I can file a PR. ^^-

**Comment by Michael-F-Bryan** [comment]
It sounds like this is functionality you care about, so I would encourage you to publish your own `tower-include-dir` crate. I don't want to add it under a feature flag because that's extra maintenance work for me and it would tie `include_dir`'s versioning to `tower` (e.g. when I publish `include_dir v1.0`, I'll need to make another major release when `tower` goes from `0.4` to `0.5`).
